kind: pipeline
name: deploy
image: focal
platform:
  os: linux
  arch: arm64

steps:
- name: "install dependencies"
  commands:
    - git g++ make build-essential
    - git clone https://github.com/WiringPi/WiringPi.git && cd WiringPi && sudo ./build
- name: "build MainStation"
  commands:
    - make