kind: pipeline
name: deploy

platform:
  os: linux
  arch: arm64

steps:
- name: "Build"
  image: ubuntu:focal
  commands:
    - apt-get update
    - apt-get install -y git g++ make build-essential sudo
    - git clone https://github.com/WiringPi/WiringPi.git && cd WiringPi && ./build
    - make -C /drone/src