version: "3.9"
services:
  webclient: "erikd256/dcch64-mainstation-integratedwebclient:latest"
   ports:
      - "80:3000"
  dccgen:
    image: "erikd256/dcch64-mainstation-dccgen:latest"
      ports: "4386:3000"
